Get user name by getpwuid instead of environment variable USER
TanmayPatil105/procfetch pull request #150
Opened 2024-05-14 08:23 UTC by youpong

# Description

`getlogin(2)` does not return the expected value.
Instead, `getpwuid(3)` can be used to retrieve the user name.

To test this, I've prepared a repository  [youpong/getuser](https://github.com/youpong/getuser).
See function `test_getlogin()` for `getlogin(2)` behavior, function `getuser()` for an example implementation in `getpwuid(3)`.
You can see the results of the multi-platform behavior in the [GitHub Actions log](https://github.com/youpong/getuser/actions).

# Related Issue

- #148

2024-05-14 08:36 UTC, youpong commented
Unit tests are failing.
The reason is that `ubuntu:latest` in Github Actions is still using `22.04 LTS`, so the `std::format` adopted in standard C++20 is not available.

2024-05-14 12:09 UTC, youpong commented
clang++ (not g++) on Ubuntu 22.04 LTS can use std::format.
I would like to propose to use clang++ for unit test.

2024-05-14 12:43 UTC, youpong commented
Coverage testing has failed. This is because it uses g++.

Maybe Ubuntu 24.04 LTS will be available in a few months, so it's a not bad idea not to take action.
What do you think?

2024-05-14 13:08 UTC, TanmayPatil105 commented
I believe we would want `procfetch` to be compatible with older distributions too, including the tests!

2024-05-14 15:35 UTC, youpong commented
I think that being available in various distributions, old and new, is not about being able to build, but about having binaries available.
And while unit testing should be checked with every commit, coverage testing should be enough to get a trend every few months.

2024-05-14 17:07 UTC, TanmayPatil105 commented
1 hour ago: https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/

2024-05-15 05:27 UTC, youpong commented
Thank you for information. I'm traveling for a couple of days. I'll take a look later.

2024-05-22 00:40 UTC, youpong commented
Added `ubuntu-24.04` as a runner host for unit testing.
`ubuntu-latest` is left as it is.

It is OK if the test succeeds on `ubuntu-24.04`, even if it fails on `ubuntu-latest`.

The OS version of `ubuntu-latest` is 22.04 now, but will be 24.04 in a few months. We will remove `ubuntu-24.04` from unit testing at that time.

2024-05-29 18:37 UTC, TanmayPatil105 requested changes

2024-05-29 18:40 UTC, TanmayPatil105 commented on src/fetch.cpp
> +        throw runtime_error(
From the user's perspective, I don't think this matters much. This will be helpful only for debugging.

2024-06-02 06:18 UTC, youpong commented on src/fetch.cpp
> +        throw runtime_error(
I agreed.

2024-06-02 06:18 UTC, youpong commented on .github/workflows/unit-test.yml
> +        os: [ macos-latest, ubuntu-24.04 ]
Yes.

2024-06-03 04:27 UTC, TanmayPatil105 requested changes

2024-06-03 04:52 UTC, youpong commented on src/Makefile.in
> +CXXFLAGS = -std=c++20 -Wall -Wextra --pedantic-errors @CXXFLAGS@
I wouldn't mind if this wasn't the last fix. :)

2024-06-03 05:02 UTC, merged